name: eeg-classification-ad
channels:
  - conda-forge
dependencies:
  - python=3.10

  # Core
  - numpy
  - pandas
  - tqdm

  # EEG Processing
  - mne
  - mne-icalabel

  # Machine Learning
  - xgboost
  - scikit-learn
  - optuna
  - matplotlib

  # Pip and pip-installed packages
  - pip
  - pip:
      # EEG Processing
      - asrpy